### ISSUE TITLE
google cloud platform: tracking to stable

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#140]
- [x] Review the [generic platform support](https://github.com/coreos/tectonic-installer/blob/master/Documentation/generic-platform.md)
- [x] [Pre-alpha](https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md#pre-alpha): get the [generic platform support](https://github.com/coreos/tectonic-installer/blob/master/Documentation/generic-platform.md) deployed
- [ ] [Alpha](https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md#alpha): get Kubernetes installed 
- [ ] [Beta](https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md#beta): get Kubernetes working in a normal setup 
- [ ] [Stable](https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md#beta): get tests passing fully

**Comment by pierrebeaucamp** [comment]
What is the status of this? The links in the description are all dead.
Is this the most up-to date document? https://github.com/coreos/tectonic-installer/tree/master/Documentation/dev/gcp

**Comment by enxebre** [comment]
Hey @pierrebeaucamp links were moved here https://coreos.com/tectonic/docs/latest/platform-lifecycle.html
Although focus is not on GCP at the moment we might revive efforts in future.
Those are the most up to date docs and the platform should be pretty much functional but unstable

**Comment by pierrebeaucamp** [comment]
Thanks for the link @enxebre. Fyi I have a working Tectonic installation deployed on GCP right now - I'd be happy to test some things out and give feedback. I will probably run some dev apps and maybe a staging environment on it soon-ish and hope to put some production code on it once we know more regarding stability. 

Reading through that doc: So far it checks off most of the 'Alpha' requirements, but I didn't run any smoke tests yet.

**Comment by sym3tri** [comment]
We're currently working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this platform for that project, but will not be continuing the effort in this repo. We'll post a link to the new repo in the README once it's ready.

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
