### ISSUE TITLE
azure: tracking to stable

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#142]
- [x] Review the [generic platform support](https://github.com/coreos/tectonic-installer/blob/master/Documentation/generic-platform.md)
- [x] [Pre-alpha](https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md#pre-alpha): get the [generic platform support](https://github.com/coreos/tectonic-installer/blob/master/Documentation/generic-platform.md) deployed
- [x] [Alpha](https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md#alpha): get Kubernetes installed 
- [ ] [Beta](https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md#beta): get Kubernetes working in a normal setup 
- [ ] [Stable](https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md#beta): get tests passing fully

**Comment by sym3tri** [comment]
azure is stable
