### ISSUE TITLE
vmware: tracking to stable

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#143]
- [x] Review the [generic platform support](https://github.com/coreos/tectonic-installer/blob/master/Documentation/generic-platform.md)
- [x] [Pre-alpha](https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md#pre-alpha): get the [generic platform support](https://github.com/coreos/tectonic-installer/blob/master/Documentation/generic-platform.md) deployed
- [ ] [Alpha](https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md#alpha): get Kubernetes installed 
- [ ] [Beta](https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md#beta): get Kubernetes working in a normal setup 
- [ ] [Stable](https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md#beta): get tests passing fully

**Comment by philips** [comment]
Need to get this merged to go to Alpha: https://github.com/coreos/tectonic-installer/pull/18

Help wanted :)

**Comment by sym3tri** [comment]
We'll consider this for the converged platform.

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
