### ISSUE TITLE
digitalocean: tracking to stable

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#144]
- [ ] Review the [generic platform support](https://github.com/coreos/tectonic-installer/blob/master/Documentation/generic-platform.md)
- [ ] [Pre-alpha](https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md#pre-alpha): get the [generic platform support](https://github.com/coreos/tectonic-installer/blob/master/Documentation/generic-platform.md) deployed
- [ ] [Alpha](https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md#alpha): get Kubernetes installed 
- [ ] [Beta](https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md#beta): get Kubernetes working in a normal setup 
- [ ] [Stable](https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md#beta): get tests passing fully

**Comment by klausenbusk** [comment]
You should properly also add a DigitalOcean flexvolume plugin, currently I'm using [rexray](https://github.com/codedellemc/rexray) which support DO block storage.

**Comment by aknuds1** [comment]
I'm interested in working on support for DigitalOcean, is there any ongoing work towards this?

**Comment by aknuds1** [comment]
Speaking of DO block storage support, Rook seems to work well for me so far, although it's alpha level at the time of writing.

**Comment by sym3tri** [comment]
We'll consider this for the converged platform but will not be continuing any efforts in _this_ repo.

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
